spring.application.name=RestAPIs
#POSTGRES_PASSWORD=1234@Harsh
#POSTGRES_USER=harsh
#POSTGRES_DB=StudentDB



spring.application.name=TestingApp

#Port configuration
server.port=8080

#DB configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/StudentDB
spring.datasource.url=jdbc:postgresql://localhost:5432/StudentDB?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=harsh
spring.datasource.password=1234@Harsh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
